#!/bin/bash

#SBATCH --job-name=template
#SBATCH --ntasks-per-node=1
#SBATCH --mem=1G
#SBATCH --time=00:15:00

set -x
set -e

time singularity exec docker://brainlife/octave:test octave main.m

echo "all done"

